spin_master_case_study:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: transformed-data-455317
      dataset: sharepoint_spinmaster
      threads: 4
      timeout_seconds: 300
      location: US                     
  target: dev